### ISSUE TITLE
DoS: Invalid JSON crashes biz server

### ISSUE THREAD

**Issue by xobs** [ionorg/ion#142]
### Your environment.
  - Version: 0.1.0
  - Browser: N/A
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?
```sh
$ echo "}" | websocat 'wss://test-server:8443/ws?peer=ccd84be5-82cd-4229-beab-c5b8b0af508f'
$
```

Logs from docker:

```
2020-04-27 06:21:50.44 INF --- Starting Biz Node ---
2020-04-27T06:21:50Z INF non-TLS WebSocketServer listening on: 0.0.0.0:8443
2020-04-27 06:21:50.441 INF Start pprof on :6060
2020-04-27 06:21:50.441 INF New Service Node Registry: etcd => [ion-etcd:2379]
2020-04-27 06:21:50.443 INF New Service Watcher: etcd => [ion-etcd:2379]
2020-04-27 06:21:50.444 INF Start service watcher => [islb].
2020-04-27 06:21:50.745 INF Etcd.keep /dc1/node/biz-wiNNcbodPz6O {"id":"biz-wiNNcbodPz6O","ip":"172.26.0.15","name":"node-biz","service":"biz"} <nil>
2020-04-27 06:21:50.745 INF Node [/dc1/node/biz-wiNNcbodPz6O] registration success!
2020-04-27 06:22:01.365 INF signal.in, id => ccd84be5-82cd-4229-beab-c5b8b0af508f
2020-04-27T06:22:01Z INF Recivied data: }

panic: invalid character '}' looking for beginning of value

goroutine 67 [running]:
github.com/cloudwebrtc/go-protoo/peer.(*Peer).handleMessage(0xc000426a50, 0xc00013ec00, 0x3, 0x600)
        /go/pkg/mod/github.com/cloudwebrtc/go-protoo@v0.0.0-20200324091126-61fe57ffd18f/peer/peer.go:99 +0x22a
reflect.Value.call(0xc187a0, 0xc0001a1200, 0x13, 0xd6c92a, 0x4, 0xc000197b20, 0x1, 0x1, 0x1, 0x0, ...)
        /usr/local/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0xc187a0, 0xc0001a1200, 0x13, 0xc000197b20, 0x1, 0x1, 0x0, 0x1, 0x0)
        /usr/local/go/src/reflect/value.go:321 +0xb4
github.com/chuckpreslar/emission.(*Emitter).Emit.func1(0xc0000a9da0, 0xc00019b200, 0xc1be60, 0xe719d0, 0xc0001a1300, 0x1, 0x1, 0xc187a0, 0xc0001a1200, 0x13)
        /go/pkg/mod/github.com/chuckpreslar/emission@v0.0.0-20170206194824-a7ddd980baf9/emitter.go:209 +0x40c
created by github.com/chuckpreslar/emission.(*Emitter).Emit
        /go/pkg/mod/github.com/chuckpreslar/emission@v0.0.0-20170206194824-a7ddd980baf9/emitter.go:184 +0x1c2
```

### What did you expect?

Invalid data shouldn't crash the server.  Instead, the connection should simply be terminated.

### What happened?

The server crashed, and needed to be manually restarted.

**Comment by jbrady42** [comment]
Fixed in #155
