### ISSUE TITLE
SFU crashes when SDP tracks have no ssrc.

### ISSUE THREAD

**Issue by tarrencev** [ionorg/ion#159]
The following line allows a client to crash the SFU by providing an SDP stream with no ssrc for a track: https://github.com/pion/ion/blob/844f99c08fec18081ba5c2c30280ddf88d7ef036/pkg/node/sfu/internal.go#L131

I'm not very familiar with SDP, is an ssrc for each track required?

error (line numbers are incorrect):
```
panic: runtime error: index out of range [0] with length 0

goroutine 56 [running]:
github.com/pion/ion/pkg/node/sfu.publish(0xc0000314a0, 0x12, 0xc00006dd90)
	/go/src/github.com/pion/ion/pkg/node/sfu/internal.go:150 +0x13f4
github.com/pion/ion/pkg/node/sfu.handleRequest.func1(0xc000031470, 0xc000031530, 0xc000031560)
	/go/src/github.com/pion/ion/pkg/node/sfu/internal.go:32 +0x2f2
github.com/cloudwebrtc/nats-protoo.(*NatsProtoo).handleRequest(0xc00038ac00, 0xc000031470, 0xc0000362a0, 0x14, 0xc0000362c0, 0x19)
	/go/pkg/mod/github.com/cloudwebrtc/nats-protoo@v0.0.0-20200328144814-d3c1c848d442/protoo.go:150 +0x1d4
github.com/cloudwebrtc/nats-protoo.(*NatsProtoo).handleMessage(0xc00038ac00, 0xc0002ed000, 0xf27, 0xf27, 0xc0000362a0, 0x14, 0xc0000362c0, 0x19)
	/go/pkg/mod/github.com/cloudwebrtc/nats-protoo@v0.0.0-20200328144814-d3c1c848d442/protoo.go:105 +0x156
github.com/cloudwebrtc/nats-protoo.(*NatsProtoo).onRequest(0xc00038ac00, 0xc0000a6640)
	/go/pkg/mod/github.com/cloudwebrtc/nats-protoo@v0.0.0-20200328144814-d3c1c848d442/protoo.go:96 +0x198
github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc00027cb00, 0xc0001d2840)
	/go/pkg/mod/github.com/nats-io/nats.go@v1.9.1/nats.go:2147 +0x330
created by github.com/nats-io/nats%2ego.(*Conn).subscribe
	/go/pkg/mod/github.com/nats-io/nats.go@v1.9.1/nats.go:2987 +0x50e
```

**Comment by adwpc** [comment]
Yep, there should be two ssrc, one for video, another for audio.
How do you reproduce the scene?

**Comment by adwpc** [comment]
fixed panic, but i think an sdp without ssrc should not work
