### ISSUE TITLE
PNC context deadline exceeded

### ISSUE THREAD

**Issue by jonahzheng** [ionorg/ion#53]
`root@iot-one:/opt/ion# /opt/ion/bin/biz -c /opt/ion/configs/biz.toml
config /opt/ion/configs/biz.toml load ok!
2020-03-14 23:27:53.715 INF --- Starting Biz Node ---
2020-03-14T23:27:53Z INF WebSocketServer listening on: 0.0.0.0:8443
2020-03-14 23:27:53.715 INF Start pprof on :6060
2020-03-14 23:27:53.715 INF New Service Node Registry: etcd => [127.0.0.1:2379]
2020-03-14 23:27:53.716 INF New Service Watcher: etcd => [127.0.0.1:2379]
2020-03-14 23:27:53.716 INF Start service watcher => [islb].
**{"level":"warn","ts":"2020-03-14T23:27:58.717+0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-7ec9fc0d-d165-4150-bf83-b1b54c84d266/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection closed"}**
2020-03-14 23:27:58.717 PNC context deadline exceeded
panic: context deadline exceeded

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1(0xc0008b4040, 0x19)
	/root/go_work/pkg/mod/github.com/rs/zerolog@v1.17.2/log.go:338 +0x4f
github.com/rs/zerolog.(*Event).msg(0xc00009e5a0, 0xc0008b4040, 0x19)
	/root/go_work/pkg/mod/github.com/rs/zerolog@v1.17.2/event.go:146 +0x200
github.com/rs/zerolog.(*Event).Msgf(0xc00009e5a0, 0xd2a258, 0x2, 0xc0000dde98, 0x1, 0x1)
	/root/go_work/pkg/mod/github.com/rs/zerolog@v1.17.2/event.go:126 +0x83
github.com/pion/ion/pkg/log.Panicf(0xd2a258, 0x2, 0xc0000dde98, 0x1, 0x1)
	/opt/ion/pkg/log/log.go:49 +0x6d
github.com/pion/ion/pkg/discovery.(*ServiceWatcher).WatchServiceNode(0xc000916c20, 0xd2ac45, 0x4, 0xd684d0)
	/opt/ion/pkg/discovery/node.go:142 +0x293
main.main()
	/opt/ion/cmd/biz/main.go:41 +0x3ab
`

**Comment by jonahzheng** [comment]
requires etcd 3.x (or later)
